import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  ActivityIndicator,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Colors } from '../../../theme/colors';
import apiClient from '../../../services/api/client';

interface Guardian {
  id: string;
  guardianEmail: string;
  guardianName: string;
  guardianVerified: boolean;
  configured?: boolean;
  verifiedAt: string | null;
}

type Step = 'list' | 'add_info' | 'email_config' | 'otp_verify';

export default function GuardianScreen() {
  const router = useRouter();

  const [guardians, setGuardians] = useState<Guardian[]>([]);
  const [loading, setLoading] = useState(true);
  const [currentStep, setCurrentStep] = useState<Step>('list');

  // Form fields
  const [guardianName, setGuardianName] = useState('');
  const [guardianEmail, setGuardianEmail] = useState('');
  const [smtpUser, setSmtpUser] = useState('');
  const [smtpAppPassword, setSmtpAppPassword] = useState('');
  const [otp, setOtp] = useState('');

  // Status flags
  const [savingConfig, setSavingConfig] = useState(false);
  const [sendingOtp, setSendingOtp] = useState(false);
  const [verifyingOtp, setVerifyingOtp] = useState(false);

  useEffect(() => {
    fetchGuardianStatus();
  }, []);

  const fetchGuardianStatus = async () => {
    try {
      setLoading(true);
      const res = await apiClient.get('/guardian/status');
      if (res.data?.success) {
        setGuardians(res.data.guardians || []);
      }
    } catch (err: any) {
      console.log('Error fetching guardian status:', err?.message);
    } finally {
      setLoading(false);
    }
  };

  const handleStep1Next = () => {
    if (!guardianName.trim()) {
      Alert.alert('Required', 'Please enter guardian\'s full name.');
      return;
    }
    if (!guardianEmail.trim() || !guardianEmail.includes('@')) {
      Alert.alert('Required', 'Please enter a valid Gmail address.');
      return;
    }
    setSmtpUser(guardianEmail.trim().toLowerCase());
    setCurrentStep('email_config');
  };

  const handleSaveConfig = async () => {
    const cleanAppPassword = smtpAppPassword.trim().replace(/\s+/g, '');
    if (!cleanAppPassword || cleanAppPassword.length < 8) {
      Alert.alert('App Password Required', 'Please enter the 16-character Gmail App Password generated by your guardian.');
      return;
    }

    try {
      setSavingConfig(true);
      const res = await apiClient.post('/guardian/email-config', {
        guardianEmail: guardianEmail.trim().toLowerCase(),
        smtpUser: smtpUser.trim().toLowerCase(),
        smtpAppPassword: cleanAppPassword,
      });

      if (res.data?.success) {
        Alert.alert('Saved!', 'Guardian email SMTP credentials saved successfully. Now tap "Send OTP".');
      }
    } catch (err: any) {
      Alert.alert('Save Failed', err?.message || 'Could not save guardian email configuration.');
    } finally {
      setSavingConfig(false);
    }
  };

  const handleSendOtp = async () => {
    try {
      setSendingOtp(true);
      const res = await apiClient.post('/guardian/send-otp', {
        email: guardianEmail.trim().toLowerCase(),
      });

      if (res.data?.success) {
        Alert.alert('OTP Sent!', `6-digit code dispatched to ${guardianEmail.trim().toLowerCase()}`);
        setCurrentStep('otp_verify');
      }
    } catch (err: any) {
      Alert.alert('OTP Failed', err?.message || 'Failed to send OTP. Ensure configuration is saved.');
    } finally {
      setSendingOtp(false);
    }
  };

  const handleVerifyOtp = async () => {
    if (!otp.trim() || otp.trim().length !== 6) {
      Alert.alert('Required', 'Please enter the 6-digit verification code.');
      return;
    }

    try {
      setVerifyingOtp(true);
      const res = await apiClient.post('/guardian/verify-otp', {
        email: guardianEmail.trim().toLowerCase(),
        otp: otp.trim(),
        guardianName: guardianName.trim(),
      });

      if (res.data?.success) {
        Alert.alert('Success 🎉', 'Family Guardian linked & verified successfully!');
        resetForm();
        fetchGuardianStatus();
      }
    } catch (err: any) {
      Alert.alert('Verification Failed', err?.message || 'Invalid or expired OTP code.');
    } finally {
      setVerifyingOtp(false);
    }
  };

  const handleRemoveGuardian = async (id: string) => {
    Alert.alert('Confirm Remove', 'Are you sure you want to remove this guardian?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Remove',
        style: 'destructive',
        onPress: async () => {
          try {
            await apiClient.delete(`/guardian/${id}`);
            fetchGuardianStatus();
          } catch (err: any) {
            Alert.alert('Error', 'Failed to remove guardian.');
          }
        },
      },
    ]);
  };

  const resetForm = () => {
    setCurrentStep('list');
    setGuardianName('');
    setGuardianEmail('');
    setSmtpUser('');
    setSmtpAppPassword('');
    setOtp('');
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView style={styles.container} contentContainerStyle={styles.content}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
            <Ionicons name="arrow-back" size={20} color={Colors.text} />
          </TouchableOpacity>
          <View style={{ flex: 1 }}>
            <Text style={styles.headerLabel}>FAMILY SAFETY MONITOR</Text>
            <Text style={styles.headerTitle}>Personal Guardian Manager</Text>
          </View>
        </View>

        {/* Banner */}
        <View style={styles.heroCard}>
          <Ionicons name="shield-checkmark" size={28} color={Colors.accent} />
          <View style={{ flex: 1 }}>
            <Text style={styles.heroTitle}>Trusted Emergency Guardians</Text>
            <Text style={styles.heroDesc}>
              Nominate contacts to receive real-time notifications for flight updates, security screening clearance, and emergency SOS alerts.
            </Text>
          </View>
        </View>

        {/* ── STEP 1: ADD GUARDIAN INFO ── */}
        {currentStep === 'add_info' && (
          <View style={styles.formCard}>
            <Text style={styles.stepHeader}>Step 1 of 3: Guardian Contact</Text>

            <Text style={styles.label}>Guardian Full Name</Text>
            <TextInput
              style={styles.input}
              value={guardianName}
              onChangeText={setGuardianName}
              placeholder="e.g. John Doe (Parent / Contact)"
              placeholderTextColor={Colors.textMuted}
            />

            <Text style={styles.label}>Guardian Gmail Address</Text>
            <TextInput
              style={styles.input}
              value={guardianEmail}
              onChangeText={setGuardianEmail}
              placeholder="guardian@gmail.com"
              keyboardType="email-address"
              autoCapitalize="none"
              placeholderTextColor={Colors.textMuted}
            />

            <View style={styles.btnRow}>
              <TouchableOpacity style={styles.cancelBtn} onPress={resetForm}>
                <Text style={styles.cancelBtnText}>Cancel</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.primaryBtn} onPress={handleStep1Next}>
                <Text style={styles.primaryBtnText}>Next: Email Setup</Text>
                <Ionicons name="arrow-forward" size={16} color="#FFFFFF" />
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* ── STEP 2: GMAIL APP PASSWORD SETUP ── */}
        {currentStep === 'email_config' && (
          <View style={styles.formCard}>
            <Text style={styles.stepHeader}>Step 2 of 3: Set Up Guardian Email Verification</Text>

            <View style={styles.infoBox}>
              <Ionicons name="information-circle" size={20} color={Colors.accent} />
              <Text style={styles.infoBoxText}>
                Ask guardian to enable 2-Step Verification on Google Account & generate a 16-character App Password for "Mail".
              </Text>
            </View>

            <Text style={styles.label}>Gmail Address</Text>
            <TextInput
              style={styles.input}
              value={smtpUser}
              onChangeText={setSmtpUser}
              placeholder="guardian@gmail.com"
              keyboardType="email-address"
              autoCapitalize="none"
              placeholderTextColor={Colors.textMuted}
            />

            <Text style={styles.label}>Gmail App Password (16 Characters)</Text>
            <TextInput
              style={styles.input}
              value={smtpAppPassword}
              onChangeText={setSmtpAppPassword}
              placeholder="xxxx xxxx xxxx xxxx"
              secureTextEntry
              autoCapitalize="none"
              placeholderTextColor={Colors.textMuted}
            />

            <TouchableOpacity style={styles.secondaryBtn} onPress={handleSaveConfig} disabled={savingConfig}>
              {savingConfig ? (
                <ActivityIndicator color={Colors.accent} />
              ) : (
                <Text style={styles.secondaryBtnText}>1. Save Email Configuration</Text>
              )}
            </TouchableOpacity>

            <TouchableOpacity style={styles.primaryBtn} onPress={handleSendOtp} disabled={sendingOtp}>
              {sendingOtp ? (
                <ActivityIndicator color="#FFFFFF" />
              ) : (
                <>
                  <Text style={styles.primaryBtnText}>2. Send Verification OTP</Text>
                  <Ionicons name="paper-plane" size={16} color="#FFFFFF" />
                </>
              )}
            </TouchableOpacity>

            <TouchableOpacity style={{ alignSelf: 'center', marginTop: 8 }} onPress={() => setCurrentStep('add_info')}>
              <Text style={{ color: Colors.textMuted, fontSize: 12 }}>← Back to Contact Info</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* ── STEP 3: OTP VERIFICATION ── */}
        {currentStep === 'otp_verify' && (
          <View style={styles.formCard}>
            <Text style={styles.stepHeader}>Step 3 of 3: Verify 6-Digit OTP Code</Text>
            <Text style={styles.subText}>Enter the OTP sent to {guardianEmail}</Text>

            <TextInput
              style={[styles.input, styles.otpInput]}
              value={otp}
              onChangeText={setOtp}
              placeholder="123456"
              keyboardType="number-pad"
              maxLength={6}
              placeholderTextColor={Colors.textMuted}
            />

            <View style={styles.btnRow}>
              <TouchableOpacity style={styles.cancelBtn} onPress={() => setCurrentStep('email_config')}>
                <Text style={styles.cancelBtnText}>Back</Text>
              </TouchableOpacity>

              <TouchableOpacity style={styles.verifyBtn} onPress={handleVerifyOtp} disabled={verifyingOtp}>
                {verifyingOtp ? (
                  <ActivityIndicator color="#FFFFFF" />
                ) : (
                  <>
                    <Ionicons name="checkmark-circle" size={18} color="#FFFFFF" />
                    <Text style={styles.primaryBtnText}>Verify & Link Guardian</Text>
                  </>
                )}
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* ── GUARDIAN LIST SCREEN ── */}
        {currentStep === 'list' && (
          <View style={styles.listSection}>
            <View style={styles.listHeader}>
              <Text style={styles.sectionTitle}>Nominated Guardians ({guardians.length})</Text>
              <TouchableOpacity style={styles.addBtn} onPress={() => setCurrentStep('add_info')}>
                <Ionicons name="add" size={16} color="#FFFFFF" />
                <Text style={styles.addBtnText}>Add Guardian</Text>
              </TouchableOpacity>
            </View>

            {loading ? (
              <ActivityIndicator color={Colors.accent} style={{ marginVertical: 24 }} />
            ) : guardians.length === 0 ? (
              <View style={styles.emptyCard}>
                <Ionicons name="people-outline" size={36} color={Colors.textMuted} />
                <Text style={styles.emptyText}>No guardians added yet.</Text>
                <Text style={styles.emptySub}>Tap "Add Guardian" to nominate a family safety contact.</Text>
              </View>
            ) : (
              guardians.map((g) => (
                <View key={g.id} style={styles.mentorItem}>
                  <View style={styles.avatar}>
                    <Text style={styles.avatarText}>{(g.guardianName || g.guardianEmail).charAt(0).toUpperCase()}</Text>
                  </View>

                  <View style={{ flex: 1 }}>
                    <Text style={styles.mentorName}>{g.guardianName || 'Family Guardian'}</Text>
                    <Text style={styles.mentorEmail}>{g.guardianEmail}</Text>

                    <View style={styles.badgeRow}>
                      <View style={[styles.badge, g.configured ? styles.badgeConfigured : styles.badgeDefault]}>
                        <Text style={styles.badgeText}>{g.configured ? 'Configured' : 'Not Configured'}</Text>
                      </View>
                      <View style={[styles.badge, g.guardianVerified ? styles.badgeVerified : styles.badgePending]}>
                        <Text style={styles.badgeText}>{g.guardianVerified ? 'Verified' : 'Pending'}</Text>
                      </View>
                    </View>
                  </View>

                  <TouchableOpacity onPress={() => handleRemoveGuardian(g.id)}>
                    <Ionicons name="trash-outline" size={20} color={Colors.danger} />
                  </TouchableOpacity>
                </View>
              ))
            )}
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  container: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  headerLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.accent,
    letterSpacing: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.text,
  },
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 16,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 20,
  },
  heroTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: 4,
  },
  heroDesc: {
    fontSize: 12,
    color: Colors.textMuted,
    lineHeight: 16,
  },
  formCard: {
    padding: 18,
    borderRadius: 20,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 12,
    marginBottom: 20,
  },
  stepHeader: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.text,
    marginBottom: 4,
  },
  subText: {
    fontSize: 12,
    color: Colors.textMuted,
  },
  infoBox: {
    flexDirection: 'row',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  infoBoxText: {
    flex: 1,
    fontSize: 11,
    color: Colors.textMuted,
    lineHeight: 16,
  },
  label: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: Colors.text,
  },
  otpInput: {
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 8,
  },
  btnRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  cancelBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.textMuted,
  },
  primaryBtn: {
    flex: 2,
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtn: {
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.accent,
    alignItems: 'center',
    justify.content: 'center',
    marginTop: 4,
  },
  secondaryBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.accent,
  },
  verifyBtn: {
    flex: 2,
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  listSection: {
    gap: 12,
  },
  listHeader: {
    flexDirection: 'row',
    justify: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.text,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  addBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  emptyCard: {
    padding: 32,
    borderRadius: 20,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: 'center',
    gap: 6,
  },
  emptyText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.text,
  },
  emptySub: {
    fontSize: 12,
    color: Colors.textMuted,
    textAlign: 'center',
  },
  mentorItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  mentorName: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.text,
  },
  mentorEmail: {
    fontSize: 12,
    color: Colors.textMuted,
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 4,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  badgeConfigured: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  badgeDefault: {
    backgroundColor: 'rgba(156, 163, 175, 0.15)',
  },
  badgeVerified: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  badgePending: {
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.text,
  },
});
